// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://regqdedsmdwgukbnjgrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZ3FkZWRzbWR3Z3VrYm5qZ3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzAxMjksImV4cCI6MjA2MzEwNjEyOX0.mO-FFmmRpkmCOfjml34_plTCrOjm-6_OBMpp8vGlxOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);